---

__maestro:
    schema: 2

name: helloworld

ship_defaults:
    socket_path: /var/run/docker.sock
    timeout: 60

ships:
    localhost:
        ip: 172.17.0.1

services:
    db_persistence:
        image: debian:jessie
        instances:
            db_1_data:
                ship: localhost
                volumes:
                    {{ env.HOME }}/docker-data-containers/db_1_data: /var/lib/mysql
                env:
                    LANG: en_US.UTF-8
    db:
        image: mariadb:10
        requires: [ db_persistence ]
        instances:
            db_1:
                ship: localhost
                ports:
                    mysql:
                        exposed: 3306
                        external: 3306
                volumes_from: [ db_1_data ]
                lifecycle:
                    running: [{type: tcp, port: mysql}]
                env:
                    MYSQL_ROOT_PASSWORD: root
                    LANG: en_US.UTF-8
    django_application_code:
        image: debian:jessie
        instances:
            django_code_1:
                ship: localhost
                volumes:
                    {{ env.PWD }}: /code
                env:
                    LANG: en_US.UTF-8
    nginx_uwsgi_django:
        image: nginx_uwsgi_django
        requires: [ db, django_application_code ]
        instances:
            nginx_uwsgi_django_1:
                ship: localhost
                ports:
                    http:
                        exposed: 80
                        external: 80
                volumes_from: [ django_code_1 ]
                lifecycle:
                    running: [{type: tcp, port: http}]
                env:
                    LANG: en_US.UTF-8
